apiVersion: v1
kind: Pod
spec:
  containers:
    - name: framework-environment-arm64v8
      image: framework-environment-arm64v8:v1
  restartPolicy: Never
  hostAliases:
    - ip: 172.17.4.194
      hostnames:
        - git.smartmatic.net
