pipeline {
  agent {
    kubernetes {
      yamlFile 'arm64v8/framework-environment.yaml'
      defaultContainer 'framework-environment-arm64v8'
    }
  }
  
  stages {
    stage('SCM checkout') {
      steps {
        git branch: '${GIT_BRANCH}',
            credentialsId: 'Git_Credentials',
            url: '${GIT_REPO_URL}'
      }
    }

    stage('Build') {
      steps {
        sh './scripts/clean.sh'
        sh './scripts/create-debug-makefiles.sh'
        sh './scripts/make.sh -j8'
        sh './scripts/create-deb-package.sh'
      }
    }
  }
}
